### ISSUE TITLE
Apply CSS Effeciently

### ISSUE THREAD

**Issue by reviewer99** [cod1cat/prj-rev-bwfs-dasmoto#5]
When writing your CSS styles, it is best to try and eliminate any duplicate styles found in your stylesheet as it makes it easier to make changes in the future.

For example here instead of the following:
```CSS
h2.brushes{
	font-size: 32px;
	font-weight: bold;
	color: white;
	background-color: mediumspringgreen;

}

h2.frames{
	font-size: 32px;
	font-weight: bold;
	color: white;
	background-color: lightcoral;
}

h2.paint{
	font-size: 32px;
	font-weight: bold;
	color: white;
	background-color: skyblue;
}
```

You could have done something like this:
```CSS
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white; 
}

.brushes {
  background-color: mediumspringgreen;
}

.frames {
  background-color: lightcoral;
}

.paint {
  background-color: skyblue;
}
```

This way all your `h2`s inherit the styles, they all share, and you only need to apply the unique background they all have.

https://github.com/cod1cat/prj-rev-bwfs-dasmoto/blob/81122c923187fcea68c88ae88688b6da1bd26ba1/Dasmotos/css/style.css#L11-L31
