### ISSUE TITLE
Missing Semicolon

### ISSUE THREAD

**Issue by reviewer99** [cod1cat/prj-rev-bwfs-dasmoto#6]
Looks like your missing a semicolon at the end of this rule

```CSS
body { 
  font-family: Helvetica;
}
```

https://github.com/cod1cat/prj-rev-bwfs-dasmoto/blob/81122c923187fcea68c88ae88688b6da1bd26ba1/Dasmotos/css/style.css#L1
